version: '3'

services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '33066:3306'
    environment:
      MYSQL_DATABASE: 'uploader'
      MYSQL_USER: 'uploader'
      MYSQL_PASSWORD: 'uploader'
      MYSQL_ROOT_PASSWORD: 'root'
      TZ: Europe/Warsaw
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/image_uploader
    ports:
      - "8000:8000"
    depends_on:
      - db